/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.locacao.devolver;

import locadora.controller.locacao.DevolverController;
import locadora.controller.veiculo.VeiculoController;

/**
 *
 * @author natan
 */
public class BotaoLocacaoDevolverView extends javax.swing.JPanel {

    /**
     * Creates new form BotaoLocacaoDevolver
     */
    public BotaoLocacaoDevolverView() {
        initComponents();
    }
    
    public void setController(DevolverController controller) {
        this.btnDevolverVeiculo.addActionListener(e -> controller.devolverVeiculo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDevolverVeiculo = new javax.swing.JButton();

        btnDevolverVeiculo.setText("Devolver veículo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDevolverVeiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDevolverVeiculo)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolverVeiculo;
    // End of variables declaration//GEN-END:variables
}
