/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.locacao.devolver;

import locadora.controller.locacao.DevolverController;
import locadora.controller.locacao.LocacaoController;

/**
 *
 * @author natan
 */
public class BotaoLocacaoPesquisarView extends javax.swing.JPanel {

    /**
     * Creates new form FormularLocacaoPesquisarView
     */
    public BotaoLocacaoPesquisarView() {
        initComponents();
    }
    
    public void setController(DevolverController controller) {
        this.btnListarLocacoes.addActionListener(e -> controller.listarLocacoes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarLocacoes = new javax.swing.JButton();

        btnListarLocacoes.setText("Listar locações");
        btnListarLocacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLocacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListarLocacoes)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnListarLocacoes)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarLocacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLocacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarLocacoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarLocacoes;
    // End of variables declaration//GEN-END:variables
}
