/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.locacao.devolver;

import java.util.List;
import javax.swing.JTable;
import locadora.model.locacao.Locacao;

/**
 *
 * @author natan
 */
public class TabelaLocacaoView extends javax.swing.JPanel {
    private DevolverVeiculoTableModel modeloTabelaDevolverVeiculo = new DevolverVeiculoTableModel();
    private JanelaDevolverView janela;
    private int linhaClicadaParaLocacao = -1;
    /**
     * Creates new form tabelaLocacaoview
     */
    public TabelaLocacaoView() {
        initComponents();
    }
    
    private void tabelaLocacaoVeiculoeMouseClicked(java.awt.event.MouseEvent evt) {                                           
        //Pega a linha clicada
        linhaClicadaParaLocacao = this.tabelaLocacao.rowAtPoint(evt.getPoint());
    }
    
    public JTable getTabelaLocacao() {
        return this.tabelaLocacao;
    }
    
    public void setJanelaView(JanelaDevolverView janela) {
        this.janela = janela;
    }
    
    public void setListaLocacoesTabela(List<Locacao> lista) {
        modeloTabelaDevolverVeiculo.setListaLocacao(lista);
    }
    
    public Locacao recuperarLocacaoSelecionada(){
        Locacao locacao = modeloTabelaDevolverVeiculo.getLocacao(this.linhaClicadaParaLocacao);
        return locacao;
    } 
    
    public void excluirLocacaoDaTabela(List<Locacao> listaParaExcluir) {
        modeloTabelaDevolverVeiculo.removeLocacoes(listaParaExcluir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLocacao = new javax.swing.JTable();

        tabelaLocacao.setModel(modeloTabelaDevolverVeiculo);
        tabelaLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLocacaoVeiculoeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLocacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLocacao;
    // End of variables declaration//GEN-END:variables

}
