/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.locacao.vender;

import javax.swing.DefaultComboBoxModel;
import locadora.controller.locacao.LocacaoController;
import locadora.model.veiculo.Categoria;
import locadora.model.veiculo.Marca;

/**
 *
 * @author natan
 */
public class FormularioPesquisaVeiculoVendaView extends javax.swing.JPanel {

    /**
     * Creates new form FormularioPesquisaVeiculoVendaView
     */
    public FormularioPesquisaVeiculoVendaView() {
        initComponents();
    }
    
    public void setController(LocacaoController controller) {
        this.btnPesquisarVeiculo.addActionListener(e -> controller.listarVeiculos());
    }
    
        public DefaultComboBoxModel<String> getModelOptions(String tipo) {
        switch (tipo) {
            case "Automovel":
                return new DefaultComboBoxModel<>(new String[] { "Gol", "Celta", "Palio", "Fiesta", "Civic", "Corolla" });
            case "Motocicleta":
                return new DefaultComboBoxModel<>(new String[] { "CG125", "CBR500", "Ninja300", "XJ6" });
            case "Van":
                return new DefaultComboBoxModel<>(new String[] { "Kombi", "Sprinter", "Ducato" });
            default:
                return new DefaultComboBoxModel<>(new String[] {});
        }
    }
    
    public void initView() {
        java.awt.EventQueue.invokeLater(() ->  this.setVisible(true));
    }
    
    private void boxTipoActionPerformed(java.awt.event.ActionEvent evt) {                                        
       
    } 
    
    public class filtrosVeiculo {

        private Marca marca;
        private Categoria categoria;
        private String tipo;

        public filtrosVeiculo(Marca marca, Categoria categoria, String tipo) {
            this.marca = marca;
            this.categoria = categoria;
            this.tipo = tipo;
        }

        public Marca getMarca() {
            return marca;
        }

        public Categoria getCategoria() {
            return categoria;
        }

        public String getTipo() {
            return tipo;
        }
    }


    public filtrosVeiculo recuperarFiltrosVeiculo() {
        Marca marca = Marca.valueOf((String) boxMarca.getSelectedItem());
        Categoria categoria = Categoria.valueOf((String) boxCategoria.getSelectedItem());
        String tipo = (String) boxTipo.getSelectedItem();
        
        return new filtrosVeiculo(marca, categoria, tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxTipo = new javax.swing.JComboBox<>();
        btnPesquisarVeiculo = new javax.swing.JButton();
        boxMarca = new javax.swing.JComboBox<>();
        boxCategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovel", "Motocicleta", "Van" }));
        boxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoActionPerformed(evt);
            }
        });

        btnPesquisarVeiculo.setText("Pesquisar veículo");

        boxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VW", "GM", "Fiat", "Honda", "Mercedes" }));

        boxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POPULAR", "INTERMEDIARIO", "LUXO" }));

        jLabel4.setText("Tipo");

        jLabel5.setText("Marca");

        jLabel6.setText("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisarVeiculo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarVeiculo)
                    .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCategoria;
    private javax.swing.JComboBox<String> boxMarca;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JButton btnPesquisarVeiculo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
