/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view.locacao.vender;

import java.util.List;
import javax.swing.WindowConstants;
import locadora.controller.veiculo.VenderController;
import locadora.model.veiculo.Veiculo;
import locadora.view.locacao.locar.FormularioPesquisaVeiculoLocacaoView;

/**
 *
 * @author natan
 */
public class JanelaVenderVeiculoView extends javax.swing.JFrame {

    /**
     * Creates new form JanelaVenderVeiculoView
     */
    public JanelaVenderVeiculoView() {
        initComponents();
    }
    
    public void setController(VenderController controller){
        this.formularioPesquisaVeiculoVendaView.setController(controller);
        this.botaoVenderVeiculoView.setController(controller);
    }
    
    public void initView() {
        /* Create and display the form */
        this.tabelaVenderView.setJanelaView(this);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.EventQueue.invokeLater(() ->  this.setVisible(true));
    }
    
    public FormularioPesquisaVeiculoVendaView.filtrosVeiculo recuperarFiltrosVeiculo() {
        return this.formularioPesquisaVeiculoVendaView.recuperarFiltrosVeiculo();
    }

    public void mostrarListaVeiculos(List<Veiculo> lista) {
        this.tabelaVenderView.setListaVeiculosTabela(lista);
    }
    
    public Veiculo recuperarVeiculoSelecionado() {
        return this.tabelaVenderView.recuperarVeiculoSelecionado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioPesquisaVeiculoVendaView = new locadora.view.locacao.vender.FormularioPesquisaVeiculoVendaView();
        tabelaVenderView = new locadora.view.locacao.vender.TabelaVenderView();
        botaoVenderVeiculoView = new locadora.view.locacao.vender.BotaoVenderVeiculoView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(formularioPesquisaVeiculoVendaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoVenderVeiculoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabelaVenderView, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formularioPesquisaVeiculoVendaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaVenderView, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoVenderVeiculoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVenderVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVenderVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVenderVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVenderVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaVenderVeiculoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private locadora.view.locacao.vender.BotaoVenderVeiculoView botaoVenderVeiculoView;
    private locadora.view.locacao.vender.FormularioPesquisaVeiculoVendaView formularioPesquisaVeiculoVendaView;
    private locadora.view.locacao.vender.TabelaVenderView tabelaVenderView;
    // End of variables declaration//GEN-END:variables

    public void excluirVeiculoTabela(Veiculo veiculo) {
        this.tabelaVenderView.excluirVeiculoTabela(veiculo);
    }
   


}
