/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.locacao.vender;

import java.util.List;
import javax.swing.JTable;
import locadora.model.veiculo.Veiculo;

/**
 *
 * @author natan
 */
public class TabelaVenderView extends javax.swing.JPanel {

    private VenderVeiculoTableModel modeloTabelaVender = new VenderVeiculoTableModel();
    private JanelaVenderVeiculoView janela;
    private int linhaClicadaParaLocacao = -1;
    /**
     * Creates new form TabelaVenderView
     */
    public TabelaVenderView() {
        initComponents();
    }
    

    
    private void tabelaVenderMouseClicked(java.awt.event.MouseEvent evt) {                                           
        //Pega a linha clicada
        linhaClicadaParaLocacao = this.tabelaVenderView.rowAtPoint(evt.getPoint());
    }
    
    public JTable getTabelaLocacaoVeiculo() {
        return this.tabelaVenderView;
    }
    
    public void setJanelaView(JanelaVenderVeiculoView janela) {
        this.janela = janela;
    }
    
    public void setListaVeiculosTabela(List<Veiculo> lista) {
        modeloTabelaVender.setListaVeiculo(lista);
    }
    
    public Veiculo recuperarVeiculoSelecionado(){
        Veiculo veiculo = modeloTabelaVender.getVeiculo(this.linhaClicadaParaLocacao);
        return veiculo;
    } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVenderView = new javax.swing.JTable();

        tabelaVenderView.setModel(modeloTabelaVender);
        tabelaVenderView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVenderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVenderView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVenderView;
    // End of variables declaration//GEN-END:variables

    void excluirVeiculoTabela(Veiculo veiculo) {
        this.modeloTabelaVender.removeVeiculo(veiculo);
    }
}
