/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view.locacao.locar;

import java.util.Calendar;
import java.util.List;
import javax.swing.WindowConstants;
import locadora.controller.locacao.LocacaoController;
import locadora.model.cliente.Cliente;
import locadora.model.veiculo.Veiculo;
import locadora.view.locacao.locar.FormularioPesquisaVeiculoLocacaoView.filtrosVeiculo;
/**
 *
 * @author natan
 */
public class JanelaLocacaoView extends javax.swing.JFrame {

    /**
     * Creates new form JanelaLocacaoView
     */
    public JanelaLocacaoView() {
        initComponents();
    }
    
    public void initView() {
        /* Create and display the form */
        this.tabelaLocacaoClienteView.setJanelaView(this);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.EventQueue.invokeLater(() ->  this.setVisible(true));
    }
    
    public void mostrarListaClientes(List<Cliente> lista) {
        this.tabelaLocacaoClienteView.setListaClientesTabela(lista);
    }
//    
    public void setController(LocacaoController controller){
        this.formularioPesquisaClienteLocacaoView.setController(controller);
        this.formularioPesquisaVeiculoLocacaoView.setController(controller);
        this.formularioLocacaoView.setController(controller);
    }
//    
//    public void limparClienteAtualizar(){
//        this.formularioPesquisaLocacaoView.limparClienteAtualizar();
//    }
//    
//    public void setListaClientesTabela(List<Cliente> lista){
//        this.formularioPesquisaLocacaoView.setListaClientesTabela(lista);
//    }
    
    public String[] recuperarFiltrosCliente(){
        return this.formularioPesquisaClienteLocacaoView.recuperarFiltrosCliente();
    }
    
    public filtrosVeiculo recuperarFiltrosVeiculo() {
        return this.formularioPesquisaVeiculoLocacaoView.recuperarFiltrosVeiculo();
    }
    
    public void mostrarListaVeiculos(List<Veiculo> lista){
        this.tabelaLocacaoVeiculoView.setListaVeiculosTabela(lista);
    }
   
    public Veiculo recuperarVeiculoSelecionado() {
        return this.tabelaLocacaoVeiculoView.recuperarVeiculoSelecionado();
    }

        
    public class DadosLocacao {

        private int dias;
        private Calendar data;
        private Cliente cliente;

        public DadosLocacao(int dias, Calendar data, Cliente cliente) {
            this.dias = dias;
            this.data = data;
            this.cliente = cliente;
        }

        public int getDias() {
            return dias;
        }

        public Calendar getData() {
            return data;
        }

        public Cliente getCliente() {
            return cliente;
        }
    }
    
    public DadosLocacao recuperarDadosLocacao(){
        int dias = this.formularioLocacaoView.recuperarDiasLocacao();
        Calendar data = this.formularioLocacaoView.recuperarDataLocacao();
        Cliente cliente = this.tabelaLocacaoClienteView.recuperarClienteSelecionado();
        
        DadosLocacao dadosLocacao = new DadosLocacao(dias, data, cliente);
        
        return dadosLocacao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioPesquisaClienteLocacaoView = new locadora.view.locacao.locar.FormularioPesquisaClienteLocacaoView();
        tabelaLocacaoClienteView = new locadora.view.locacao.locar.TabelaLocacaoClienteView();
        formularioPesquisaVeiculoLocacaoView = new locadora.view.locacao.locar.FormularioPesquisaVeiculoLocacaoView();
        tabelaLocacaoVeiculoView = new locadora.view.locacao.locar.TabelaLocacaoVeiculoView();
        formularioLocacaoView = new locadora.view.locacao.locar.FormularioLocacaoView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formularioLocacaoView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(formularioPesquisaClienteLocacaoView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabelaLocacaoClienteView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formularioPesquisaVeiculoLocacaoView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabelaLocacaoVeiculoView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formularioPesquisaClienteLocacaoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaLocacaoClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formularioPesquisaVeiculoLocacaoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaLocacaoVeiculoView, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formularioLocacaoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaLocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaLocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaLocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaLocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaLocacaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private locadora.view.locacao.locar.FormularioLocacaoView formularioLocacaoView;
    private locadora.view.locacao.locar.FormularioPesquisaClienteLocacaoView formularioPesquisaClienteLocacaoView;
    private locadora.view.locacao.locar.FormularioPesquisaVeiculoLocacaoView formularioPesquisaVeiculoLocacaoView;
    private locadora.view.locacao.locar.TabelaLocacaoClienteView tabelaLocacaoClienteView;
    private locadora.view.locacao.locar.TabelaLocacaoVeiculoView tabelaLocacaoVeiculoView;
    // End of variables declaration//GEN-END:variables


}
