/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.locacao.locar;

import java.util.List;
import javax.swing.JTable;
import locadora.model.cliente.Cliente;
import locadora.model.veiculo.Veiculo;

/**
 *
 * @author natan
 */
public class TabelaLocacaoVeiculoView extends javax.swing.JPanel {
    private LocacaoVeiculoTableModel modeloTabelaLocacaoVeiculo = new LocacaoVeiculoTableModel();
    private JanelaLocacaoView janela;
    private int linhaClicadaParaLocacao = -1;
    /**
     * Creates new form TabelaLocacaoVeiculoView
     */
    public TabelaLocacaoVeiculoView() {
        initComponents();
    }
    
    private void tabelaLocacaoVeiculoeMouseClicked(java.awt.event.MouseEvent evt) {                                           
        //Pega a linha clicada
        linhaClicadaParaLocacao = this.tabelaLocacaoVeiculo.rowAtPoint(evt.getPoint());
    }
    
    public JTable getTabelaLocacaoVeiculo() {
        return this.tabelaLocacaoVeiculo;
    }
    
    public void setJanelaView(JanelaLocacaoView janela) {
        this.janela = janela;
    }
    
    public void setListaVeiculosTabela(List<Veiculo> lista) {
        modeloTabelaLocacaoVeiculo.setListaVeiculo(lista);
    }
    
    public Veiculo recuperarVeiculoSelecionado(){
        Veiculo veiculo = modeloTabelaLocacaoVeiculo.getVeiculo(this.linhaClicadaParaLocacao);
        return veiculo;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLocacaoVeiculo = new javax.swing.JTable();

        tabelaLocacaoVeiculo.setModel(modeloTabelaLocacaoVeiculo);
        tabelaLocacaoVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLocacaoVeiculoeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLocacaoVeiculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLocacaoVeiculo;
    // End of variables declaration//GEN-END:variables
}
