/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.locacao.locar;

import locadora.model.cliente.Cliente;
import javax.swing.JTable;
import java.util.List;

/**
 *
 * @author natan
 */
public class TabelaLocacaoClienteView extends javax.swing.JPanel {
    private LocacaoClienteTableModel modeloTabelaLocacaoCliente = new LocacaoClienteTableModel();
    private JanelaLocacaoView janela;
    private int linhaClicadaParaAtualizacao = -1;

    /**
     * Creates new form TabelaLocacaoClienteView
     */
    public TabelaLocacaoClienteView() {
        initComponents();
    }
    
    private void tabelaLocacaoClienteMouseClicked(java.awt.event.MouseEvent evt) {                                           
        //Pega a linha clicada
        linhaClicadaParaAtualizacao = this.tabelaLocacaoCliente.rowAtPoint(evt.getPoint());
        //Pega o contato da linha clicada
    }  
    
    public Cliente recuperarClienteSelecionado(){
        Cliente cliente = modeloTabelaLocacaoCliente.getCliente(linhaClicadaParaAtualizacao);
        return cliente;
    }
    
    public JTable getTabelaLocacaoCliente() {
        return this.tabelaLocacaoCliente;
    }
    
    public void setJanelaView(JanelaLocacaoView janela) {
        this.janela = janela;
    }
    
    public void setListaClientesTabela(List<Cliente> lista) {
        modeloTabelaLocacaoCliente.setListaCliente(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLocacaoCliente = new javax.swing.JTable();

        tabelaLocacaoCliente.setModel(modeloTabelaLocacaoCliente);
        tabelaLocacaoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLocacaoClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLocacaoCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLocacaoCliente;
    // End of variables declaration//GEN-END:variables
}
