/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view;
import locadora.controller.MenuController;
import locadora.view.cliente.JanelaClienteView;
import locadora.view.veiculo.JanelaVeiculoView;
/**
 *
 * @author Cristhian
 */
public class MenuView extends javax.swing.JPanel {

    private MenuController menuController;
    /**
     * Creates new form MenuView
     */
    public MenuView(MenuController menuController) {
        this.menuController = menuController;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadCliente = new javax.swing.JButton();
        btnCadVeiculo = new javax.swing.JButton();
        btnAluVeiculo = new javax.swing.JButton();
        btnDevVeiculo = new javax.swing.JButton();
        btnVenVeiculo = new javax.swing.JButton();

        btnCadCliente.setText("CADASTRAR CLIENTE");
        btnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteActionPerformed(evt);
            }
        });

        btnCadVeiculo.setText("CADASTRAR VEÍCULO");
        btnCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVeiculoActionPerformed(evt);
            }
        });

        btnAluVeiculo.setText("ALUGAR VEÍCULO");
        btnAluVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluVeiculoActionPerformed(evt);
            }
        });

        btnDevVeiculo.setText("DEVOLVER VEÍCULO");
        btnDevVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevVeiculoActionPerformed(evt);
            }
        });

        btnVenVeiculo.setText("VENDER VEÍCULO");
        btnVenVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnCadCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVenVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAluVeiculo)
                .addGap(12, 12, 12)
                .addComponent(btnDevVeiculo)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAluVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVenVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteActionPerformed
        menuController.abrirJanelaCliente();
    }//GEN-LAST:event_btnCadClienteActionPerformed

    private void btnVenVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenVeiculoActionPerformed
        menuController.abrirJanelaVender();
    }//GEN-LAST:event_btnVenVeiculoActionPerformed

    private void btnCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVeiculoActionPerformed
        menuController.abrirJanelaVeiculo();
    }//GEN-LAST:event_btnCadVeiculoActionPerformed

    private void btnAluVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluVeiculoActionPerformed
        menuController.abrirJanelaLocacao();
    }//GEN-LAST:event_btnAluVeiculoActionPerformed

    private void btnDevVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevVeiculoActionPerformed
        // TODO add your handling code here:
        menuController.abrirJanelaDevolver();
    }//GEN-LAST:event_btnDevVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluVeiculo;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadVeiculo;
    private javax.swing.JButton btnDevVeiculo;
    private javax.swing.JButton btnVenVeiculo;
    // End of variables declaration//GEN-END:variables
}
